language: cpp
sudo: false
services:
  - docker

script: ./build.sh
deploy:
  provider: releases
  api_key:
    secure: WIcKpGJXWURSMaMZzSbmEQoEzORPMSH13/iSUPfqHYwAaNp4Xa70E2l7Gg3xGs+LQe00uZSfT5pcvazLDlq/wmb2CWu3UP6R368JrvfMpvMRQXvuZz5Bd8GXKLcvHVp8fHYDCLiOw2P/2drTu+IshSJrzuxlIPZgnNzcSlpKqf5DQB4aAirNgdYHPlwFfIpjyFiFupSqIJ/zOqNyIyeCqjCYm6Zw8Bn03r/gosPrChbKHaUch5WXlmL2qBqSCjovf2jg+EtXmM4zE908/yfD/UYZhKxN7Ld54AzXSamEI5zt/UkDw1qOkoQR9Kud9HPCE6EjkH1qEH0ynpn95Vz6RMkcfnNnejW3OoZM8350xFZQ1+tay0IEOtXQn1F7NlVGPi//FYjatlnpRx6j8YmZLiqvR03g8c4lIkG57xcs2BzHlUqVIaHJN+g6LE11IpTsAOP2smw68F08wQ0xfe1XNhICQ25S4n11PdA63z/4z4PqajXoBJF3+laazFVIUZR0eW6Ws33VWE8L0fBeZokDAvzp/GDwsbSbE81MZBSFnWO6fdHpnrzhkSkY5LFSd4uxvmAXbNw8I7FYDx4VUa8xL1EfpphMcRvqCnJfNvJiWITd9s6KA324zkiPOKfY2KChBIJ/evDHXeANqYT80KA+1U/j1Fq0GXm3maRCdDLjS3I=
  file: 'hello.exe'
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^vc3.*$"
